import type { CarMetadata } from "@/data/car-metadata"

// Auto-generated by scripts/fetch_car_metadata.py
// Source: https://www.automobiledimension.com/
export const carMetadataAutoById: Record<string, CarMetadata> = {
  "seat-seat-leon": {
    bodyType: "compacto",
    lengthMm: 4368,
    widthMm: 1799,
    trunkLiters: 380,
    imageUrl: "https://www.automobiledimension.com/photos/seat-leon-2020.jpg",
  },
  "hyundai-i20": {
    bodyType: "utilitario",
    lengthMm: 4065,
    widthMm: 1775,
    trunkLiters: 352,
    imageUrl: "https://www.automobiledimension.com/photos/hyundai-i20-2023.jpg",
  },
  "volkswagen-t-cross": {
    bodyType: "suv-urbano",
    lengthMm: 4127,
    widthMm: 1760,
    trunkLiters: 385,
    imageUrl:
      "https://www.automobiledimension.com/photos/volkswagen-t-cross-2024.jpg",
  },
  "renault-austral": {
    bodyType: "suv-compacto",
    lengthMm: 4533,
    widthMm: 1830,
    trunkLiters: 500,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-austral-2025.jpg",
  },
  "skoda-kamiq": {
    bodyType: "suv-compacto",
    lengthMm: 4241,
    widthMm: 1793,
    trunkLiters: 400,
    imageUrl: "https://www.automobiledimension.com/photos/skoda-kamiq-2024.jpg",
  },
  "renault-captur": {
    bodyType: "suv-compacto",
    lengthMm: 4239,
    widthMm: 1797,
    trunkLiters: 422,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-captur-2024.jpg",
  },
  "tesla-model-3": {
    bodyType: "compacto",
    lengthMm: 4720,
    widthMm: 1850,
    trunkLiters: 513,
    imageUrl:
      "https://www.automobiledimension.com/photos/tesla-model-3-2024.jpg",
  },
  "peugeot-208-5p-allure-gasolina": {
    bodyType: "utilitario",
    lengthMm: 4055,
    widthMm: 1745,
    trunkLiters: 309,
    imageUrl: "https://www.automobiledimension.com/photos/peugeot-208-2024.jpg",
  },
  "ford-kuga": {
    bodyType: "suv-compacto",
    lengthMm: 4604,
    widthMm: 1882,
    trunkLiters: 482,
    imageUrl: "https://www.automobiledimension.com/photos/ford-kuga-2024.jpg",
  },
  "mg-mg-hs": {
    bodyType: "suv-compacto",
    lengthMm: 4670,
    widthMm: 1890,
    trunkLiters: 507,
    imageUrl: "https://www.automobiledimension.com/photos/mg-hs-2025.jpg",
  },
  "kia-niro": {
    bodyType: "suv-compacto",
    lengthMm: 4420,
    widthMm: 1825,
    trunkLiters: 495,
    imageUrl: "https://www.automobiledimension.com/photos/kia-niro-2022.jpg",
  },
  "skoda-fabia": {
    bodyType: "compacto",
    lengthMm: 4108,
    widthMm: 1780,
    trunkLiters: 380,
    imageUrl: "https://www.automobiledimension.com/photos/skoda-fabia-2021.jpg",
  },
  "ford-puma": {
    bodyType: "suv-urbano",
    lengthMm: 4186,
    widthMm: 1805,
    trunkLiters: 574,
    imageUrl: "https://www.automobiledimension.com/photos/ford-puma-2024.jpg",
  },
  "nissan-nissan-juke": {
    bodyType: "suv-compacto",
    lengthMm: 4210,
    widthMm: 1800,
    trunkLiters: 422,
    imageUrl: "https://www.automobiledimension.com/photos/nissan-juke-2024.jpg",
  },
  "byd-byd-seal-u-dm-i": {
    bodyType: "suv-compacto",
    lengthMm: 4785,
    widthMm: 1890,
    trunkLiters: 425,
    imageUrl: "https://www.automobiledimension.com/photos/byd-seal-u-2024.jpg",
  },
  "opel-corsa-gs-1-2t-xhl-mt6": {
    bodyType: "utilitario",
    lengthMm: 4060,
    widthMm: 1765,
    trunkLiters: 309,
    imageUrl: "https://www.automobiledimension.com/photos/opel-corsa-2024.jpg",
  },
  "peugeot-2008-allure-hybrid-145": {
    bodyType: "suv-compacto",
    lengthMm: 4304,
    widthMm: 1770,
    trunkLiters: 434,
    imageUrl:
      "https://www.automobiledimension.com/photos/peugeot-2008-2023.jpg",
  },
  "jeep-avenger": {
    bodyType: "suv-urbano",
    lengthMm: 4084,
    widthMm: 1776,
    trunkLiters: 380,
    imageUrl:
      "https://www.automobiledimension.com/photos/jeep-avenger-2023.jpg",
  },
  "volvo-xc40": {
    bodyType: "suv-compacto",
    lengthMm: 4440,
    widthMm: 1863,
    trunkLiters: 452,
    imageUrl: "https://www.automobiledimension.com/photos/volvo-xc40-2023.jpg",
  },
  "renault-captur-e-tech-hybrid": {
    bodyType: "suv-compacto",
    lengthMm: 4239,
    widthMm: 1797,
    trunkLiters: 422,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-captur-2024.jpg",
  },
  "skoda-karoq": {
    bodyType: "suv-compacto",
    lengthMm: 4390,
    widthMm: 1841,
    trunkLiters: 521,
    imageUrl: "https://www.automobiledimension.com/photos/skoda-karoq-2022.jpg",
  },
  "mazda-mazda-cx-30": {
    bodyType: "suv-compacto",
    lengthMm: 4395,
    widthMm: 1795,
    trunkLiters: 430,
    imageUrl: "https://www.automobiledimension.com/photos/mazda-cx-30-2020.jpg",
  },
  "citroen-nuevo-c4-hybrid-145": {
    bodyType: "compacto",
    lengthMm: 4360,
    widthMm: 1800,
    trunkLiters: 380,
    imageUrl: "https://www.automobiledimension.com/photos/citroen-c4-2021.jpg",
  },
  "renault-symbioz": {
    bodyType: "suv-compacto",
    lengthMm: 4413,
    widthMm: 1797,
    trunkLiters: 613,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-symbioz-2025.jpg",
  },
  "citroen-nuevo-citro-n-c3-turbo": {
    bodyType: "utilitario",
    lengthMm: 4015,
    widthMm: 1755,
    trunkLiters: 310,
    imageUrl: "https://www.automobiledimension.com/photos/citroen-c3-2024.jpg",
  },
  "volkswagen-caddy": {
    lengthMm: 4500,
    widthMm: 1855,
    trunkLiters: 1385,
    imageUrl:
      "https://www.automobiledimension.com/photos/volkswagen-caddy-2021.jpg",
  },
  "tesla-model-y": {
    bodyType: "suv-compacto",
    lengthMm: 4790,
    widthMm: 1920,
    trunkLiters: 971,
    imageUrl:
      "https://www.automobiledimension.com/photos/tesla-model-y-2025.jpg",
  },
  "audi-a3-sportback": {
    bodyType: "compacto",
    lengthMm: 4352,
    widthMm: 1816,
    trunkLiters: 380,
    imageUrl:
      "https://www.automobiledimension.com/photos/audi-a3-sportback-2024.jpg",
  },
  "hyundai-i10": {
    bodyType: "utilitario",
    lengthMm: 3670,
    widthMm: 1680,
    trunkLiters: 252,
    imageUrl: "https://www.automobiledimension.com/photos/hyundai-i10-2023.jpg",
  },
  "audi-a1-sportback": {
    bodyType: "utilitario",
    lengthMm: 4029,
    widthMm: 1740,
    trunkLiters: 335,
    imageUrl:
      "https://www.automobiledimension.com/photos/audi-a1-sportback-2019.jpg",
  },
  "ford-focus": {
    bodyType: "compacto",
    lengthMm: 4382,
    widthMm: 1825,
    trunkLiters: 392,
    imageUrl: "https://www.automobiledimension.com/photos/ford-focus-2022.jpg",
  },
  "seat-seat-ateca": {
    bodyType: "suv-compacto",
    lengthMm: 4381,
    widthMm: 1841,
    trunkLiters: 510,
    imageUrl: "https://www.automobiledimension.com/photos/seat-ateca-2020.jpg",
  },
  "cupra-formentor": {
    bodyType: "suv-compacto",
    lengthMm: 4451,
    widthMm: 1839,
    trunkLiters: 450,
    imageUrl:
      "https://www.automobiledimension.com/photos/cupra-formentor-2024.jpg",
  },
  "mg-mg3-hybrid": {
    bodyType: "compacto",
    lengthMm: 4113,
    widthMm: 1797,
    trunkLiters: 293,
    imageUrl: "https://www.automobiledimension.com/photos/mg-mg3-2024.jpg",
  },
  "volkswagen-polo": {
    bodyType: "utilitario",
    lengthMm: 4074,
    widthMm: 1751,
    trunkLiters: 351,
    imageUrl:
      "https://www.automobiledimension.com/photos/volkswagen-polo-2021.jpg",
  },
  "dacia-jogger": {
    bodyType: "suv-compacto",
    lengthMm: 4547,
    widthMm: 1784,
    trunkLiters: 708,
    imageUrl:
      "https://www.automobiledimension.com/photos/dacia-jogger-2022.jpg",
  },
  "peugeot-2008-allure-gasolina-1": {
    bodyType: "suv-compacto",
    lengthMm: 4304,
    widthMm: 1770,
    trunkLiters: 434,
    imageUrl:
      "https://www.automobiledimension.com/photos/peugeot-2008-2023.jpg",
  },
  "mercedes-benz-glc-300-de-4matic": {
    bodyType: "suv-compacto",
    lengthMm: 4731,
    widthMm: 1890,
    trunkLiters: 500,
    imageUrl:
      "https://www.automobiledimension.com/photos/mercedes-benz-glc-coupe-2019.jpg",
  },
  "kia-xceed": {
    bodyType: "suv-compacto",
    lengthMm: 4395,
    widthMm: 1826,
    trunkLiters: 426,
    imageUrl: "https://www.automobiledimension.com/photos/kia-xceed-2023.jpg",
  },
  "volkswagen-touran": {
    bodyType: "compacto",
    lengthMm: 4527,
    widthMm: 1829,
    trunkLiters: 743,
    imageUrl:
      "https://www.automobiledimension.com/photos/volkswagen-touran-2016.jpg",
  },
  "kia-ev3": {
    bodyType: "suv-compacto",
    lengthMm: 4300,
    widthMm: 1850,
    trunkLiters: 485,
    imageUrl: "https://www.automobiledimension.com/photos/kia-ev3-2025.jpg",
  },
  "audi-q3-sportback": {
    bodyType: "suv-compacto",
    lengthMm: 4531,
    widthMm: 1859,
    trunkLiters: 488,
    imageUrl:
      "https://www.automobiledimension.com/photos/audi-q3-sportback-2026.jpg",
  },
  "fiat-600": {
    bodyType: "compacto",
    lengthMm: 4171,
    widthMm: 1781,
    trunkLiters: 385,
    imageUrl: "https://www.automobiledimension.com/photos/fiat-600-2024.jpg",
  },
  "citroen-nuevo-citro-n-c3-aircr": {
    bodyType: "utilitario",
    lengthMm: 4015,
    widthMm: 1755,
    trunkLiters: 310,
    imageUrl: "https://www.automobiledimension.com/photos/citroen-c3-2024.jpg",
  },
  "cupra-cupra-leon": {
    bodyType: "compacto",
    lengthMm: 4398,
    widthMm: 1799,
    trunkLiters: 380,
    imageUrl: "https://www.automobiledimension.com/photos/cupra-leon--2024.jpg",
  },
  "audi-q2": {
    bodyType: "suv-compacto",
    lengthMm: 4208,
    widthMm: 1794,
    trunkLiters: 405,
    imageUrl: "https://www.automobiledimension.com/photos/audi-q2-2021.jpg",
  },
  "peugeot-208-5p-allure-hybrid-1": {
    bodyType: "utilitario",
    lengthMm: 4055,
    widthMm: 1745,
    trunkLiters: 309,
    imageUrl: "https://www.automobiledimension.com/photos/peugeot-208-2024.jpg",
  },
  "dacia-bigster": {
    bodyType: "suv-compacto",
    lengthMm: 4570,
    widthMm: 1810,
    trunkLiters: 667,
    imageUrl:
      "https://www.automobiledimension.com/photos/dacia-bigster-2025.jpg",
  },
  "hyundai-bayon": {
    bodyType: "suv-urbano",
    lengthMm: 4180,
    widthMm: 1775,
    trunkLiters: 411,
    imageUrl:
      "https://www.automobiledimension.com/photos/hyundai-bayon-2024.jpg",
  },
  "opel-corsa-edition-1-2t-xhl": {
    bodyType: "utilitario",
    lengthMm: 4060,
    widthMm: 1765,
    trunkLiters: 309,
    imageUrl: "https://www.automobiledimension.com/photos/opel-corsa-2024.jpg",
  },
  "skoda-octavia": {
    bodyType: "compacto",
    lengthMm: 4698,
    widthMm: 1829,
    trunkLiters: 600,
    imageUrl:
      "https://www.automobiledimension.com/photos/skoda-octavia-2024.jpg",
  },
  "mercedes-benz-glc-220-d-4matic": {
    bodyType: "suv-compacto",
    lengthMm: 4731,
    widthMm: 1890,
    trunkLiters: 500,
    imageUrl:
      "https://www.automobiledimension.com/photos/mercedes-benz-glc-coupe-2019.jpg",
  },
  "bmw-x1-sdrive20d": {
    bodyType: "suv-compacto",
    lengthMm: 4500,
    widthMm: 1845,
    trunkLiters: 540,
    imageUrl: "https://www.automobiledimension.com/photos/bmw-x1-2023.jpg",
  },
  "volvo-xc60": {
    bodyType: "suv-compacto",
    lengthMm: 4708,
    widthMm: 1902,
    trunkLiters: 483,
    imageUrl: "https://www.automobiledimension.com/photos/volvo-xc60-2025.jpg",
  },
  "renault-rafale": {
    bodyType: "suv-compacto",
    lengthMm: 4710,
    widthMm: 1866,
    trunkLiters: 530,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-rafale-2024.jpg",
  },
  "nissan-nissan-x-trail": {
    bodyType: "suv-compacto",
    lengthMm: 4680,
    widthMm: 1840,
    trunkLiters: 585,
    imageUrl:
      "https://www.automobiledimension.com/photos/nissan-x-trail-2023.jpg",
  },
  "renault-arkana-e-tech": {
    bodyType: "suv-compacto",
    lengthMm: 4568,
    widthMm: 1821,
    trunkLiters: 513,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-arkana-2021.jpg",
  },
  "cupra-formentor-e-hybrid": {
    bodyType: "suv-compacto",
    lengthMm: 4451,
    widthMm: 1839,
    trunkLiters: 450,
    imageUrl:
      "https://www.automobiledimension.com/photos/cupra-formentor-2024.jpg",
  },
  "peugeot-nuevo-3008-allure-hybr": {
    bodyType: "suv-compacto",
    lengthMm: 4542,
    widthMm: 1895,
    trunkLiters: 520,
    imageUrl:
      "https://www.automobiledimension.com/photos/peugeot-3008-2024.jpg",
  },
  "mazda-mazda3": {
    bodyType: "compacto",
    lengthMm: 4460,
    widthMm: 1795,
    trunkLiters: 358,
    imageUrl: "https://www.automobiledimension.com/photos/mazda-3-2019.jpg",
  },
  "renault-kangoo": {
    lengthMm: 4486,
    widthMm: 1860,
    trunkLiters: 850,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-kangoo-2021.jpg",
  },
  "renault-renault-5-e-tech-elect": {
    bodyType: "utilitario",
    lengthMm: 3922,
    widthMm: 1774,
    trunkLiters: 277,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-5-e-tech-2024.jpg",
  },
  "byd-byd-dolphin-surf": {
    bodyType: "utilitario",
    lengthMm: 3990,
    widthMm: 1720,
    trunkLiters: 308,
    imageUrl:
      "https://www.automobiledimension.com/photos/byd-dolphin-surf-2025.jpg",
  },
  "mg-mg3": {
    bodyType: "compacto",
    lengthMm: 4113,
    widthMm: 1797,
    trunkLiters: 293,
    imageUrl: "https://www.automobiledimension.com/photos/mg-mg3-2024.jpg",
  },
  "skoda-kodiaq": {
    bodyType: "suv-compacto",
    lengthMm: 4758,
    widthMm: 1864,
    trunkLiters: 725,
    imageUrl:
      "https://www.automobiledimension.com/photos/skoda-kodiaq-2024.jpg",
  },
  "mercedes-benz-gla-250-e": {
    bodyType: "suv-compacto",
    lengthMm: 4410,
    widthMm: 1834,
    trunkLiters: 435,
    imageUrl:
      "https://www.automobiledimension.com/photos/mercedes-benz-gla-2020.jpg",
  },
  "citroen-nuevo-c4-hybrid-136": {
    bodyType: "compacto",
    lengthMm: 4360,
    widthMm: 1800,
    trunkLiters: 380,
    imageUrl: "https://www.automobiledimension.com/photos/citroen-c4-2021.jpg",
  },
  "fiat-panda": {
    bodyType: "utilitario",
    lengthMm: 3686,
    widthMm: 1672,
    trunkLiters: 225,
    imageUrl: "https://www.automobiledimension.com/photos/fiat-panda-2021.jpg",
  },
  "audi-q3": {
    bodyType: "suv-compacto",
    lengthMm: 4531,
    widthMm: 1859,
    trunkLiters: 488,
    imageUrl: "https://www.automobiledimension.com/photos/audi-q3-2026.jpg",
  },
  "lexus-lexus-lbx": {
    bodyType: "suv-urbano",
    lengthMm: 4190,
    widthMm: 1825,
    trunkLiters: 332,
    imageUrl: "https://www.automobiledimension.com/photos/lexus-lbx-2024.jpg",
  },
  "renault-clio-e-tech-hybrid": {
    bodyType: "utilitario",
    lengthMm: 3922,
    widthMm: 1774,
    trunkLiters: 277,
    imageUrl:
      "https://www.automobiledimension.com/photos/renault-5-e-tech-2024.jpg",
  },
  "cupra-terramar-e-hybrid": {
    bodyType: "suv-compacto",
    lengthMm: 4519,
    widthMm: 1869,
    trunkLiters: 540,
    imageUrl:
      "https://www.automobiledimension.com/photos/cupra-terramar-2025.jpg",
  },
  "toyota-toyota-aygo-x": {
    bodyType: "utilitario",
    lengthMm: 3776,
    widthMm: 1740,
    trunkLiters: 231,
    imageUrl:
      "https://www.automobiledimension.com/photos/toyota-aygo-x-cross-2026.jpg",
  },
  "hyundai-i-30": {
    bodyType: "compacto",
    lengthMm: 4340,
    widthMm: 1795,
    trunkLiters: 395,
    imageUrl: "https://www.automobiledimension.com/photos/hyundai-i30-2020.jpg",
  },
} as const
