// Auto-generated by scripts/build_sales_rolling_12m.py
// Source: DGT monthly microdata files in data/dgt/monthly

export const rollingSalesWindowMonths = 12 as const
export const rollingSalesStartMonth = "2025-02" as const
export const rollingSalesEndMonth = "2026-01" as const
export const rollingSalesLabel = "Feb 2025 - Ene 2026" as const

export const rollingSalesUnitsByCarId = {
  "dacia-sandero": 37975,
  "renault-clio": 28265,
  "seat-ibiza": 24553,
  "mg-zs": 23179,
  "toyota-corolla": 21976,
  "seat-arona": 21302,
  "peugeot-2008": 21262,
  "hyundai-tucson": 21248,
  "nissan-qashqai": 20743,
  "toyota-c-hr": 20587,
  "peugeot-208": 20512,
  "toyota-yaris-cross": 19608,
  "renault-captur": 18999,
} as const

export const rollingSalesRankByCarId = {
  "dacia-sandero": 1,
  "renault-clio": 2,
  "seat-ibiza": 3,
  "mg-zs": 4,
  "toyota-corolla": 5,
  "seat-arona": 6,
  "peugeot-2008": 7,
  "hyundai-tucson": 8,
  "nissan-qashqai": 9,
  "toyota-c-hr": 10,
  "peugeot-208": 11,
  "toyota-yaris-cross": 12,
  "renault-captur": 13,
} as const
